# Copyright 2021 METRO Digital GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 38b88246ccc552bffaaf54259d064beeee434539  # frozen: v4.0.1
  hooks:
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: ['--fix', 'lf']
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 74aa46422e41f7dd6f2df7c029d28cb096989c5b  # frozen: v1.55.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_tfsec
    - id: terraform_docs
- repo: https://github.com/thlorenz/doctoc
  rev: 3ce6bef59b0a6ef79c9d8ba28c31f108acaadb63  # frozen: v2.1.0
  hooks:
    - id: doctoc
      args: ['--github', '--title', '## Table of Contents', '--update-only']
