# This file was generated by the booostrap.sh script from the
# https://github.com/metro-digital/terraform-google-cf-projectcfg repository

provider "google" {
  project                     = local.project_id
  impersonate_service_account = local.iac_service_account
}

provider "google-beta" {
  project                     = local.project_id
  impersonate_service_account = local.iac_service_account
}
